#!/bin/bash
#
# Sample program 
#
# Name b1 - first exercise script
#
echo ""
date
echo ""
echo You ran the process with the following command:
echo $0 $*
echo The first argument is $1
echo The second argument is $2
echo "How many arguments are there?"
echo ""
sleep 3
echo 'I can tell because the special variable $# is set to the'
echo number of arguments typed in on the command line
echo So the number of arguments is $#
exit 0
