#!/bin/bash
# temperature conversion
typeset -i ftemp
typeset -i ctemp
typeset -i intemp
ftemp=0
ctemp=0
intemp=0

if [ $# -gt 1 ]
then
	echo "Usage $0 number"
	echo "   or $0"	
	exit
fi

if [ $# -eq 1 ]
then
	intemp=$1
    else
	echo -n "Give temperature: "
	read intemp
fi	

(( ctemp=(intemp-32)*5/9 ))
(( ftemp=(intemp/5)*9+32 ))

echo "Temperature (degrees F)  $ftemp"
echo "Converts to (degrees C)  $ctemp"
exit 0
