#!/bin/bash
# hour
case  ` date  +%H `
in
        0? | 1[01] ) echo "Good morning Oh healthy one";;
        1[2-7] ) echo "Good afternoon Oh wealthy one";;
        * ) echo " good evening Oh tired one";;
esac
exit 0
