#!/bin/sh
# Sample answer for while loop question
echo This script will sum all directories entered
total=0
count=0
while true
do
	read -p "Please enter a directory: " inum
	if [ $inum = q ]; then
		break
	fi
	if [ -d $inum ]; then
		dirsize=`du -sk $inum | awk '{print $1}'`
		total=`expr $total + $dirsize`
		count=`expr $count + 1`
	else
		echo $inum is not a directory - not included
	fi
done
echo Total of directory sizes = $total
echo Number of directories entered was $count
exit 0
